// Generated by Selenium IDE
import org.checkerframework.common.value.qual.StaticallyExecutable;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AutorizationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","F:/chromedriver/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void autorization() {
    driver.get("https://05.ru/");
    driver.manage().window().setSize(new Dimension(1280, 762));
    {
      WebElement element = driver.findElement(By.linkText("Условия возврата"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Вход")).click();
    driver.findElement(By.name("AUTH[LOGIN]")).click();
    driver.findElement(By.cssSelector(".bem-modal_active")).click();
    driver.findElement(By.name("AUTH[PASSWORD]")).click();
    driver.findElement(By.cssSelector(".bem-form:nth-child(4) .bem-button")).click();
    driver.findElement(By.linkText("Выход")).click();
    {
      WebElement element = driver.findElement(By.linkText("Вход"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }

    @Test
  public void testGoogleSearch() throws InterruptedException {
    // Optional. If not specified, WebDriver searches the PATH for chromedriver.
    //System.setProperty("webdriver.chrome.driver", "C://Program Files//Java//chromedriver");
      System.setProperty("webdriver.chrome.driver", "C:/WebDriver/bin/chromedriver");

    //WebDriver driver = new ChromeDriver();
      WebDriver driver = new ChromeDriver();
    //driver.get("http://www.google.com/");
//    Thread.sleep(5000);  // Let the user actually see something!
//    WebElement searchBox = driver.findElement(By.name("q"));
//    searchBox.sendKeys("ChromeDriver");
//    searchBox.submit();
//    Thread.sleep(5000);  // Let the user actually see something!
//    driver.quit();
  }
}
