// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTest {

  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before

  public void setUp() {
    driver = new FirefoxDriver();

    //System.setProperty("webdriver.Firefox.driver","F:/chromedriver/chromedriver.exe");
    System.setProperty("webdriver.gecko.driver", "F:/TESTS//geckodriver.exe");

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() {
    driver.get("https://05.ru/");
    driver.manage().window().setSize(new Dimension(550, 692));
    driver.findElement(By.linkText("Вход")).click();
    driver.findElement(By.name("AUTH[LOGIN]")).click();
    driver.findElement(By.name("AUTH[LOGIN]")).sendKeys("79884449824");
    driver.findElement(By.name("AUTH[PASSWORD]")).click();
    driver.findElement(By.name("AUTH[PASSWORD]")).sendKeys("Qa123123");
    driver.findElement(By.cssSelector(".bem-form:nth-child(4) .bem-button")).click();
  }
}
